server:
  port: 8088

spring:
  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/museum?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;DatabaseName=museum
    username: root
    password: 123456
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.museum.entity

logging:
  level:
    com.example.museum.mapper: debug #打印sql

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#  endpoint:
#    shutdown:
#      enabled: true
#netty:
#  websocket:
#    # Websocket服务端口
#    port: 9035
#    # 绑定的网卡
#    ip: 10.129.0.110
#    # 消息帧最大体积
#    max-frame-size: 10240
#    # URI路径
#    path: /channel

#mqtt:
#  username: admin
#    password: public
#    host-url: tcp://123.123.123.123:1883		# 你自己服务器的地址和端口，这个需要改
#    clientID: test							# 这个改不改随意，但不同的客户端肯定不能一样
#    default-topic: test						# 默认主题
#    timeout: 100
#    keepalive: 100
